import NavBar from "../components/NavBar/NavBar";
import "./home.scss";

const Home = () => {
  return (
    <div className="home">
        <NavBar/>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet connnnnnnnnnnnnnnnnnnnnsectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor voluptatibus, totam quos quidem soluta consequuntur et quam eligendi adipisci aperiam cupiditate accusantium neque quod nobis libero fugiat accusamus odio dicta?
    </div>
  )
}

export default Home